### ISSUE TITLE
SMTP Errors

### ISSUE THREAD

**Issue by dognutz** [linuxserver/docker-snipe-it#20]
## Expected Behavior
Test email should send successfully.

## Current Behavior
Fails with "Error: undefined."

If I enable the debug flag for Snipe-IT I can see an error saying:
"LOG.error: Swift_TransportException: Expected response code 250 but got code "501", with message "501 5.5.2 <my.hostname:8080>: Helo command rejected: Invalid name"

## Steps to Reproduce
Configure SMTP email via environment variables.
Start container.
Click 'Test Email' on setup.

However, leaving all the environment variables the same but switching to the official snipe/snipe-it image makes it work, so issue would appear to be with this image. Thanks.

**Comment by thelamer** [comment]
Can you do me a favor and try the new image with new env variables: 
```
NGINX_APP_URL=my.hostname:8080
APP_URL=http://my.hostname:8080
```
I think the software might be using the APP_URL directive to determine where to ping into and we had to roll that over to our own variable to not conflict.

**Comment by ryanmerolle** [comment]
I recently converted from the docker-compose setup provided by snipe-it to this image due to some abstraction of complexity & the uid/gid flexibility.

If I deploy with the current release from linuxserver.io.  If I create the env file with the suggested NGINX_APP_URL and the APP_URL as mentioned above, I get the following error:

> Uh oh! Snipe-IT thinks your URL is https://snipeit.localhost, but your real URL is https://app_url_placeholder/setup Please update your APP_URL settings in your .env file

I suspect that the APP_URL env variable is having issues.

```bash
NGINX_APP_URL=https://snipeit.localhost
APP_URL=https://snipeit.localhost
```

Once I get over this hurdle I can help test the SMTP issue mentioned above.

**Comment by ryanmerolle** [comment]
interesting enough `echo $APP_URL` shows the right output in the container

**Comment by ryanmerolle** [comment]
looks to be the same problem for ls127

**Comment by ryanmerolle** [comment]
It seems the `40-config` has a `sed: bad option in substitution expression` per the docker logs.
